name: Process only 1 date for DFO
description: Reduce processing time

runs:
  using: "composite"
  steps:
    - name: Reduce processing time
      shell: bash
      run: |
        python <<'EOF'
        import os
        file_path = os.path.join(".", "DFO_tool.py")

        # Text replacements
        replacements = {
            "datelist = generate_procesing_list()": "datelist = list(generate_procesing_list().keys())[:1]"
        }

        # Read file
        with open(file_path, "r", encoding="utf-8") as f:
            content = f.read()

        for old, new in replacements.items():
            content = content.replace(old, new)

        # Write file
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(content)
        EOF