name: Stop HWRF before MoM_update
description: Reduce processing time

runs:
  using: "composite"
  steps:
    - name: Reduce processing time, stop before MoM_update
      shell: bash
      run: |
        python <<'EOF'
        import os
        file_path = os.path.join(".", "HWRF_MoM.py")

        # Text replacements
        replacements = {
            "GFMS_fixdate(adate[:8])": "import sys; sys.exit()"
        }

        # Read file
        with open(file_path, "r", encoding="utf-8") as f:
            content = f.read()

        for old, new in replacements.items():
            content = content.replace(old, new)

        # Write file
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(content)
        EOF