server:
    bind:
        host: 127.0.0.1
        port: 5000
    url: __PUBLIC_URL__
    mimetype: application/json; charset=UTF-8
    encoding: utf-8
    language: en-US
    cors: true
    pretty_print: false
    limit: 1000
    map:
        url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
        attribution: '&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'

logging:
    level: WARNING

metadata:
    identification:
        title: MoM Watershed API
        description: Watershed boundaries for MoM flood alert
        keywords:
            - watersheds
            - flood
        keywords_type: theme
        terms_of_service: null
        url: ''
    license:
        name: CC-BY 4.0
        url: https://creativecommons.org/licenses/by/4.0/
    provider:
        name: MoM Production
        url: null
    contact:
        name: null
        position: null
        address: null
        city: null
        stateorprovince: null
        postalcode: null
        country: null
        phone: null
        fax: null
        email: null
        url: null
        hours: null
        instructions: null
        role: pointOfContact

resources:
    watersheds:
        type: collection
        title: Watersheds
        description: Global watershed boundaries
        keywords:
            - watersheds
        links: []
        extents:
            spatial:
                bbox: [-180, -90, 180, 90]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
        providers:
            - type: feature
              name: OGR
              data:
                  source_type: ESRI Shapefile
                  source: ../data/watershed_shp/Watershed_pfaf_id.shp
                  source_srs: EPSG:4326
                  target_srs: EPSG:4326
                  source_capabilities:
                      paging: True
                  gdal_ogr_options:
                      EMPTY_AS_NULL: NO
                      GDAL_CACHEMAX: 256
                      CPL_DEBUG: NO
              id_field: pfaf_id
              layer: Watershed_pfaf_id