name: Reduce number of VIIRS images
description: Reduce processing time

runs:
  using: "composite"
  steps:
    - name: Reduce processing time, stop before MoM_update
      shell: bash
      run: |
        python <<'EOF'
        import os
        file_path = os.path.join(".", "VIIRS_tool.py")

        # Text replacements
        replacements = {
            "for i in range(1, 137):": "for i in range(1, 3):",
            "update_VIIRS_MoM(adate)": "import sys; sys.exit()"
        }

        # Read file
        with open(file_path, "r", encoding="utf-8") as f:
            content = f.read()

        for old, new in replacements.items():
            content = content.replace(old, new)

        # Write file
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(content)
        EOF