#!/usr/bin/env python3
"""
serve_cog_nginx.py
==================
Generate a minimal Nginx configuration and start/stop a local Nginx process
that serves the COG image folder over HTTP.

The COG root is derived from DATA_DIR in first_setup/db_setup/db_config.cfg
(sibling directory: <parent of DATA_DIR>/cog_images), identical to the path
used by upload_local_images.py.

Only .tiff / .tif files are served.  Directory listing is disabled.  All other
paths return 403.  CORS and Accept-Ranges headers are set so COG clients can
perform HTTP range requests against individual tiles and overview levels.

Usage:
    python database_update/serve_cog_nginx.py start   [--port PORT]
    python database_update/serve_cog_nginx.py stop
    python database_update/serve_cog_nginx.py status
    python database_update/serve_cog_nginx.py config  # print generated config only

Defaults:
    --port  8090
"""

import argparse
import os
import re
import signal
import subprocess
import sys
import tempfile
from pathlib import Path

# ---------------------------------------------------------------------------
# Shared path helpers (same logic as upload_local_images.py)
# ---------------------------------------------------------------------------

_DB_CFG_PATH        = Path(__file__).parent.parent / "first_setup" / "db_setup" / "db_config.cfg"
# _SAMPLE_DB_CFG_PATH = Path(__file__).parent.parent / "first_setup" / "db_setup" / "sample_db_config.cfg"

# Runtime files written next to this script so they are easy to locate
_SCRIPT_DIR = Path(__file__).parent
_PID_FILE   = _SCRIPT_DIR / "nginx_cog.pid"
_CFG_FILE   = _SCRIPT_DIR / "nginx_cog.conf"
_ERROR_LOG  = _SCRIPT_DIR / "nginx_cog_error.log"
_ACCESS_LOG = _SCRIPT_DIR / "nginx_cog_access.log"

DEFAULT_PORT = 8090


def _parse_shell_cfg(path: Path) -> dict:
    """Parse a shell-style key="value" config file into a dict."""
    result = {}
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        m = re.match(r'^(\w+)\s*=\s*"?([^"#]*)"?\s*(?:#.*)?$', line)
        if m:
            result[m.group(1)] = m.group(2).strip()
    return result


def _get_cog_root() -> Path:
    """Derive the COG root from DATA_DIR in db_config.cfg."""
    cfg_path = _DB_CFG_PATH # if _DB_CFG_PATH.exists() else _SAMPLE_DB_CFG_PATH
    if not cfg_path.exists():
        print(
            "ERROR: db_config.cfg not found.\n"
            f"  Looked for: {_DB_CFG_PATH}\n",
            # f"  Fallback:   {_SAMPLE_DB_CFG_PATH}",
            file=sys.stderr,
        )
        sys.exit(1)

    cfg = _parse_shell_cfg(cfg_path)
    data_dir = cfg.get("DATA_DIR")
    if not data_dir:
        print(f"ERROR: DATA_DIR not found in {cfg_path}", file=sys.stderr)
        sys.exit(1)

    return Path(data_dir).expanduser().parent / "cog_images"


# ---------------------------------------------------------------------------
# Nginx config generation
# ---------------------------------------------------------------------------

_NGINX_CONF_TEMPLATE = """\
# Auto-generated by serve_cog_nginx.py — do not edit by hand.
# Serves Cloud-Optimized GeoTIFF files from {cog_root}

worker_processes  1;
pid               {pid_file};
error_log         {error_log}  warn;

events {{
    worker_connections  256;
}}

http {{
    access_log  {access_log};

    # MIME type for GeoTIFF
    types {{
        image/tiff  tif tiff;
    }}
    default_type  application/octet-stream;

    sendfile            on;
    tcp_nopush          on;
    keepalive_timeout   65;

    # Disable emitting the Nginx version in headers and error pages
    server_tokens       off;

    server {{
        listen       {port};
        server_name  localhost 127.0.0.1;

        # Serve COG files from the configured root
        root    {cog_root};

        # Disable directory listing — no browsing allowed
        autoindex  off;

        # --- COG tile endpoint ---
        # Accepts any .tiff / .tif path; returns the file with headers that
        # enable HTTP range requests (required by COG readers such as GDAL
        # VSI/curl, rio-cogeo, Titiler, etc.)
        location ~* \\.tiff?$ {{
            # Range support is built into Nginx; the header below advertises it
            add_header  Accept-Ranges       bytes          always;

            # CORS — allow any origin to make range requests (typical for web maps)
            add_header  Access-Control-Allow-Origin        "*"            always;
            add_header  Access-Control-Allow-Methods       "GET, HEAD, OPTIONS" always;
            add_header  Access-Control-Allow-Headers       "Range"        always;
            add_header  Access-Control-Expose-Headers      "Content-Length, Content-Range, Accept-Ranges" always;

            # Short cache: COG files may be updated daily
            expires     1h;
            add_header  Cache-Control  "public, max-age=3600"  always;
        }}

        # Block preflight OPTIONS at root level
        location = / {{
            if ($request_method = OPTIONS) {{
                add_header  Access-Control-Allow-Origin  "*";
                add_header  Access-Control-Allow-Methods "GET, HEAD, OPTIONS";
                add_header  Access-Control-Allow-Headers "Range";
                return 204;
            }}
            return 403;
        }}

        # Deny everything else — no other directories are exposed
        location / {{
            return 403;
        }}
    }}
}}
"""


def _build_config(cog_root: Path, port: int) -> str:
    return _NGINX_CONF_TEMPLATE.format(
        cog_root   = cog_root,
        port       = port,
        pid_file   = _PID_FILE,
        error_log  = _ERROR_LOG,
        access_log = _ACCESS_LOG,
    )


# ---------------------------------------------------------------------------
# Process management
# ---------------------------------------------------------------------------

def _nginx_bin() -> str:
    """Return the nginx executable path, or exit with an error."""
    for candidate in ("nginx", "/usr/sbin/nginx", "/usr/local/sbin/nginx"):
        try:
            subprocess.run(
                [candidate, "-v"],
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
                check=True,
            )
            return candidate
        except (FileNotFoundError, subprocess.CalledProcessError):
            continue
    print("ERROR: nginx not found. Install it with: apt install nginx", file=sys.stderr)
    sys.exit(1)


def _read_pid() -> int | None:
    if _PID_FILE.exists():
        try:
            return int(_PID_FILE.read_text().strip())
        except ValueError:
            pass
    return None


def _is_running(pid: int) -> bool:
    try:
        os.kill(pid, 0)
        return True
    except (ProcessLookupError, PermissionError):
        return False


# ---------------------------------------------------------------------------
# Commands
# ---------------------------------------------------------------------------

def cmd_config(cog_root: Path, port: int) -> None:
    print(_build_config(cog_root, port))


def cmd_start(cog_root: Path, port: int) -> None:
    if not cog_root.exists():
        print(f"ERROR: COG root does not exist: {cog_root}", file=sys.stderr)
        print("Run upload_local_images.py first to generate COG files.", file=sys.stderr)
        sys.exit(1)

    pid = _read_pid()
    if pid and _is_running(pid):
        print(f"Already running (pid {pid}). Use 'stop' first to restart.")
        return

    nginx = _nginx_bin()

    # Write config
    conf_text = _build_config(cog_root, port)
    _CFG_FILE.write_text(conf_text)

    # Test config before starting
    result = subprocess.run(
        [nginx, "-t", "-c", str(_CFG_FILE.resolve())],
        capture_output=True, text=True,
    )
    if result.returncode != 0:
        print("ERROR: nginx config test failed:\n" + result.stderr, file=sys.stderr)
        sys.exit(1)

    # Start
    subprocess.run([nginx, "-c", str(_CFG_FILE.resolve())], check=True)
    print(f"Nginx COG server started on port {port}")
    print(f"Serving : {cog_root}")
    print(f"Config  : {_CFG_FILE}")
    print(f"PID file: {_PID_FILE}")
    print(f"Logs    : {_ERROR_LOG}  /  {_ACCESS_LOG}")


def cmd_stop() -> None:
    pid = _read_pid()
    if pid is None:
        print("No PID file found — server may not be running.")
        return
    if not _is_running(pid):
        print(f"Process {pid} is not running. Removing stale PID file.")
        _PID_FILE.unlink(missing_ok=True)
        return
    os.kill(pid, signal.SIGTERM)
    print(f"Sent SIGTERM to nginx (pid {pid}).")
    _PID_FILE.unlink(missing_ok=True)


def cmd_status() -> None:
    pid = _read_pid()
    if pid is None:
        print("Status: stopped (no PID file).")
        return
    if _is_running(pid):
        print(f"Status: running (pid {pid}).")
    else:
        print(f"Status: not running (stale PID {pid}).")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Manage the local Nginx server for COG image serving."
    )
    parser.add_argument(
        "command",
        choices=["start", "stop", "status", "config"],
        help="Action to perform.",
    )
    parser.add_argument(
        "--port",
        type=int,
        default=DEFAULT_PORT,
        help=f"Port to listen on (default: {DEFAULT_PORT}).",
    )
    args = parser.parse_args()

    cog_root = _get_cog_root()

    if args.command == "config":
        cmd_config(cog_root, args.port)
    elif args.command == "start":
        cmd_start(cog_root, args.port)
    elif args.command == "stop":
        cmd_stop()
    elif args.command == "status":
        cmd_status()


if __name__ == "__main__":
    main()
