name: Replace GFMS dates to 2025
description: Replaces dates in GFMS_tool.py with available values (year 2025)

runs:
  using: "composite"
  steps:
    - name: Replace dates in GFMS_tool.py
      shell: bash
      run: |
        python <<'EOF'
        import os
        from datetime import datetime, timedelta
        file_path = os.path.join(".", "GFMS_tool.py")

        # Text replacements
        year_month = (datetime.utcnow() if datetime.utcnow().day >= 20 
              else (datetime.utcnow().replace(day=1) - timedelta(days=1))
             ).strftime("%Y%m")
        replacements = {
            "(settings.GLOFAS_PROC_DIR, txt)": "(settings.GLOFAS_PROC_DIR, txt.replace(year_month, '202511'))",
            "job_list.append((txt": "job_list.append((txt.replace(year_month, '202511')"
        }

        # Read file
        with open(file_path, "r", encoding="utf-8") as f:
            content = f.read()

        for old, new in replacements.items():
            content = content.replace(old, new)

        # Write file
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(content)
        EOF